<a href="https://colab.research.google.com/github/RMKEC111722203119/Condensation-Aware-Intelligent-Thermoelectric-Cooler-for-PC/blob/main/PMResearch1_merge_and_sort.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
param=5

In [ ]:
df1 = pd.read_csv(f"/content/drive/MyDrive/A Sen data/20 load/24/{param}v 20p.csv", encoding='latin1')
df1

,Timestamp,DHT11_Temp (°C),Humidity (%),DS18B20_Temp (°C),DewPoint (°C),Status
0,2025-10-10 12:15:54,34.2,42.0,30.06,19.64,SAFE
1,2025-10-10 12:15:56,34.2,42.0,30.12,19.64,SAFE
2,2025-10-10 12:15:58,34.2,42.0,30.19,19.64,SAFE
3,2025-10-10 12:16:00,34.2,42.0,30.25,19.64,SAFE
4,2025-10-10 12:16:02,34.2,42.0,30.25,19.64,SAFE
...,...,...,...,...,...,...
295,2025-10-10 12:26:00,35.2,42.0,31.25,20.54,SAFE
296,2025-10-10 12:26:02,35.2,42.0,31.25,20.54,SAFE
297,2025-10-10 12:26:04,35.2,42.0,31.19,20.54,SAFE
298,2025-10-10 12:26:06,35.2,42.0,31.25,20.54,SAFE
299,2025-10-10 12:26:08,35.2,42.0,31.25,20.54,SAFE

In [ ]:
df2 = pd.read_csv(f"/content/drive/MyDrive/A Sys data/20 load/24cwithpeltier/{param}V 20p.csv", encoding='latin1')
df2

,Timestamp,Core1_Temp_C,Core1_Load_pct,Core2_Temp_C,Core2_Load_pct,Package_Temp_C,Package_Power_W,CPU_Total_Load_pct
0,2025-09-23 10:13:01,15.0,3.91,9.0,3.12,15.0,2.97,3.52
1,2025-09-23 10:13:03,17.0,100.00,13.0,100.00,17.0,5.39,100.00
2,2025-09-23 10:13:05,18.0,100.00,13.0,100.00,17.0,5.00,100.00
3,2025-09-23 10:13:07,18.0,100.00,13.0,100.00,18.0,5.15,100.00
4,2025-09-23 10:13:09,18.0,100.00,13.0,100.00,17.0,5.32,100.00
...,...,...,...,...,...,...,...,...
329,2025-09-23 10:22:58,19.0,100.00,16.0,100.00,19.0,5.22,100.00
330,2025-09-23 10:23:02,20.0,100.00,15.0,100.00,20.0,4.90,100.00
331,2025-09-23 10:23:04,19.0,62.80,15.0,62.30,18.0,5.00,62.55
332,2025-09-23 10:23:06,17.0,12.31,13.0,13.08,17.0,3.80,12.69
333,2025-09-23 10:23:08,18.0,36.92,16.0,55.61,19.0,4.62,46.26

In [ ]:
import pandas as pd

# Ensure Timestamp is datetime in both dataframes
df1['Timestamp'] = pd.to_datetime(df1['Timestamp'])
df2['Timestamp'] = pd.to_datetime(df2['Timestamp'])

# Merge on Timestamp
merged = pd.merge(df1, df2, on='Timestamp', how='inner')
merged.drop(merged.index[:5], inplace=True)
# Optional: Check result
merged

,Timestamp,DHT11_Temp (°C),Humidity (%),DS18B20_Temp (°C),DewPoint (°C),Status,Core1_Temp_C,Core1_Load_pct,Core2_Temp_C,Core2_Load_pct,Package_Temp_C,Package_Power_W,CPU_Total_Load_pct
5,2025-09-23 10:13:11,19.8,69.0,18.69,14.00,SAFE,19.0,100.00,13.0,100.00,19.0,5.35,100.00
6,2025-09-23 10:13:13,19.8,69.0,18.69,14.00,SAFE,18.0,100.00,13.0,100.00,18.0,5.36,100.00
7,2025-09-23 10:13:15,19.8,69.0,18.69,14.00,SAFE,18.0,100.00,15.0,100.00,19.0,4.93,100.00
8,2025-09-23 10:13:16,19.8,69.0,18.69,14.00,SAFE,19.0,100.00,15.0,100.00,18.0,5.07,100.00
9,2025-09-23 10:13:18,19.8,69.0,18.69,14.00,SAFE,19.0,100.00,13.0,100.00,19.0,5.08,100.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,2025-09-23 10:22:58,19.4,66.0,18.37,12.94,SAFE,19.0,100.00,16.0,100.00,19.0,5.22,100.00
185,2025-09-23 10:23:02,19.4,66.0,18.37,12.94,SAFE,20.0,100.00,15.0,100.00,20.0,4.90,100.00
186,2025-09-23 10:23:04,19.4,66.0,18.37,12.94,SAFE,19.0,62.80,15.0,62.30,18.0,5.00,62.55
187,2025-09-23 10:23:06,19.4,65.0,18.44,12.71,SAFE,17.0,12.31,13.0,13.08,17.0,3.80,12.69
188,2025-09-23 10:23:08,19.4,65.0,18.44,12.71,SAFE,18.0,36.92,16.0,55.61,19.0,4.62,46.26

In [ ]:
merged['Core1_Load_pct'] = merged['Core1_Load_pct'].replace(100.00, 20)
merged['Core2_Load_pct'] = merged['Core2_Load_pct'].replace(100.00, 20)
display(merged.head())

,Timestamp,DHT11_Temp (°C),Humidity (%),DS18B20_Temp (°C),DewPoint (°C),Status,Core1_Temp_C,Core1_Load_pct,Core2_Temp_C,Core2_Load_pct,Package_Temp_C,Package_Power_W,CPU_Total_Load_pct
5,2025-09-23 10:13:11,19.8,69.0,18.69,14.0,SAFE,19.0,20.0,13.0,20.0,19.0,5.35,100.0
6,2025-09-23 10:13:13,19.8,69.0,18.69,14.0,SAFE,18.0,20.0,13.0,20.0,18.0,5.36,100.0
7,2025-09-23 10:13:15,19.8,69.0,18.69,14.0,SAFE,18.0,20.0,15.0,20.0,19.0,4.93,100.0
8,2025-09-23 10:13:16,19.8,69.0,18.69,14.0,SAFE,19.0,20.0,15.0,20.0,18.0,5.07,100.0
9,2025-09-23 10:13:18,19.8,69.0,18.69,14.0,SAFE,19.0,20.0,13.0,20.0,19.0,5.08,100.0

In [ ]:
if param==10:
  param=11

In [ ]:
print(param)

5

In [ ]:
merged['volt'] = param
display(merged.head())

,Timestamp,DHT11_Temp (°C),Humidity (%),DS18B20_Temp (°C),DewPoint (°C),Status,Core1_Temp_C,Core1_Load_pct,Core2_Temp_C,Core2_Load_pct,Package_Temp_C,Package_Power_W,CPU_Total_Load_pct,volt
5,2025-09-23 10:13:11,19.8,69.0,18.69,14.0,SAFE,19.0,20.0,13.0,20.0,19.0,5.35,100.0,5
6,2025-09-23 10:13:13,19.8,69.0,18.69,14.0,SAFE,18.0,20.0,13.0,20.0,18.0,5.36,100.0,5
7,2025-09-23 10:13:15,19.8,69.0,18.69,14.0,SAFE,18.0,20.0,15.0,20.0,19.0,4.93,100.0,5
8,2025-09-23 10:13:16,19.8,69.0,18.69,14.0,SAFE,19.0,20.0,15.0,20.0,18.0,5.07,100.0,5
9,2025-09-23 10:13:18,19.8,69.0,18.69,14.0,SAFE,19.0,20.0,13.0,20.0,19.0,5.08,100.0,5

In [ ]:
merged.to_csv(f"/content/drive/MyDrive/A Merged data/20 load/24/{param}v 20p",index=False)

In [ ]:
merged_sorted = merged.sort_values(by=['Core1_Temp_C', 'Core2_Temp_C','Humidity (%)'], ascending=[ True, True,False])
display(merged_sorted)

In [ ]:
merged_sorted.to_csv(f"/content/drive/MyDrive/A sorted data/20 load/24/{param}v 20p",index=False)

In [ ]:
result15=merged_sorted.head(15)
result15

,Timestamp,DHT11_Temp (°C),Humidity (%),DS18B20_Temp (°C),DewPoint (°C),Status,Core1_Temp_C,Core1_Load_pct,Core2_Temp_C,Core2_Load_pct,Package_Temp_C,Package_Power_W,CPU_Total_Load_pct,volt
187,2025-09-23 10:23:06,19.4,65.0,18.44,12.71,SAFE,17.0,12.31,13.0,13.08,17.0,3.80,12.69,5
14,2025-09-23 10:13:27,19.8,69.0,18.69,14.00,SAFE,17.0,20.00,16.0,20.00,18.0,5.12,100.00,5
6,2025-09-23 10:13:13,19.8,69.0,18.69,14.00,SAFE,18.0,20.00,13.0,20.00,18.0,5.36,100.00,5
12,2025-09-23 10:13:24,19.8,69.0,18.69,14.00,SAFE,18.0,20.00,13.0,20.00,19.0,5.18,100.00,5
13,2025-09-23 10:13:26,19.8,69.0,18.69,14.00,SAFE,18.0,20.00,13.0,20.00,18.0,5.17,100.00,5
19,2025-09-23 10:13:37,19.8,69.0,18.69,14.00,SAFE,18.0,20.00,13.0,20.00,18.0,5.20,100.00,5
7,2025-09-23 10:13:15,19.8,69.0,18.69,14.00,SAFE,18.0,20.00,15.0,20.00,19.0,4.93,100.00,5
23,2025-09-23 10:13:44,19.8,69.0,18.69,14.00,SAFE,18.0,20.00,15.0,20.00,18.0,5.10,100.00,5
64,2025-09-23 10:14:58,19.4,69.0,18.56,13.62,SAFE,18.0,20.00,15.0,20.00,18.0,4.82,100.00,5
155,2025-09-23 10:20:51,19.4,66.0,18.44,12.94,SAFE,18.0,20.00,15.0,20.00,19.0,5.10,100.00,5
182,2025-09-23 10:22:40,19.4,65.0,18.44,12.71,SAFE,18.0,20.00,15.0,20.00,18.0,5.33,100.00,5
16,2025-09-23 10:13:31,19.8,69.0,18.69,14.00,SAFE,18.0,20.00,16.0,20.00,18.0,5.00,100.00,5
26,2025-09-23 10:13:50,19.8,69.0,18.69,14.00,SAFE,18.0,20.00,16.0,20.00,19.0,5.23,100.00,5
89,2025-09-23 10:16:28,19.8,67.0,18.62,13.55,SAFE,18.0,20.00,16.0,20.00,18.0,5.12,100.00,5
153,2025-09-23 10:20:47,19.4,66.0,18.44,12.94,SAFE,18.0,20.00,16.0,20.00,19.0,4.97,100.00,5

In [ ]:
result5=merged_sorted.head(5)
result5

,Timestamp,DHT11_Temp (°C),Humidity (%),DS18B20_Temp (°C),DewPoint (°C),Status,Core1_Temp_C,Core1_Load_pct,Core2_Temp_C,Core2_Load_pct,Package_Temp_C,Package_Power_W,CPU_Total_Load_pct,volt
5,2025-10-09 11:47:29,24.5,60.0,21.75,16.31,SAFE,37.0,80.0,35.0,80.0,37.0,10.09,100.0,5
6,2025-10-09 11:47:31,24.5,60.0,21.75,16.31,SAFE,37.0,80.0,36.0,80.0,37.0,10.03,100.0,5
8,2025-10-09 11:47:45,24.5,60.0,21.75,16.31,SAFE,37.0,80.0,36.0,80.0,37.0,10.04,100.0,5
7,2025-10-09 11:47:43,24.5,60.0,21.75,16.31,SAFE,38.0,80.0,36.0,80.0,38.0,10.06,100.0,5
9,2025-10-09 11:47:53,24.5,60.0,21.69,16.31,SAFE,38.0,80.0,36.0,80.0,38.0,10.03,100.0,5

In [ ]:
# result15.to_csv("/content/drive/MyDrive/A Dataset/final15",index=False)
# result5.to_csv("/content/drive/MyDrive/A Dataset/final5",index=False)

In [ ]:

# Path of the CSV file in the "A dataset" folder
csv_file_path = "/content/drive/MyDrive/A Dataset/final15"

# Load the existing CSV data into a dataframe
df_existing = pd.read_csv(csv_file_path)

# Append the result15 dataframe to the existing one
df_combined = pd.concat([df_existing, result15], ignore_index=True)

# Save the combined dataframe back to the same CSV file (overwrite)
df_combined.to_csv(csv_file_path, index=False)

In [ ]:
csv_file_path = "/content/drive/MyDrive/A Dataset/final15"

# Load the existing CSV data into a dataframe
df_existing = pd.read_csv(csv_file_path)

df_existing

,Timestamp,DHT11_Temp (°C),Humidity (%),DS18B20_Temp (°C),DewPoint (°C),Status,Core1_Temp_C,Core1_Load_pct,Core2_Temp_C,Core2_Load_pct,Package_Temp_C,Package_Power_W,CPU_Total_Load_pct,volt
0,2025-09-22 14:22:50,21.8,57.0,19.94,12.98,SAFE,23.0,20.0,19.0,20.0,25.0,5.05,100.0,3
1,2025-09-22 14:15:12,21.0,62.0,19.00,13.51,SAFE,23.0,20.0,20.0,20.0,25.0,4.97,100.0,3
2,2025-09-22 14:18:56,21.5,59.0,18.94,13.22,SAFE,24.0,20.0,19.0,20.0,24.0,5.09,100.0,3
3,2025-09-22 14:21:26,21.4,59.0,19.87,13.13,SAFE,24.0,20.0,19.0,20.0,24.0,5.06,100.0,3
4,2025-09-22 14:21:28,21.4,59.0,19.87,13.13,SAFE,24.0,20.0,19.0,20.0,24.0,5.30,100.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,2025-09-23 10:22:40,19.4,65.0,18.44,12.71,SAFE,18.0,20.0,15.0,20.0,18.0,5.33,100.0,5
101,2025-09-23 10:13:31,19.8,69.0,18.69,14.00,SAFE,18.0,20.0,16.0,20.0,18.0,5.00,100.0,5
102,2025-09-23 10:13:50,19.8,69.0,18.69,14.00,SAFE,18.0,20.0,16.0,20.0,19.0,5.23,100.0,5
103,2025-09-23 10:16:28,19.8,67.0,18.62,13.55,SAFE,18.0,20.0,16.0,20.0,18.0,5.12,100.0,5
104,2025-09-23 10:20:47,19.4,66.0,18.44,12.94,SAFE,18.0,20.0,16.0,20.0,19.0,4.97,100.0,5

In [ ]:
csv_file_path = "/content/drive/MyDrive/A Dataset/final5"

# Load the existing CSV data into a dataframe
df_existing = pd.read_csv(csv_file_path)

# Append the result15 dataframe to the existing one
df_combined = pd.concat([df_existing, result5], ignore_index=True)

# Save the combined dataframe back to the same CSV file (overwrite)
df_combined.to_csv(csv_file_path, index=False)

In [ ]:
csv_file_path = "/content/drive/MyDrive/A Dataset/final5"

df_existing = pd.read_csv(csv_file_path)
df_existing

,Timestamp,DHT11_Temp (°C),Humidity (%),DS18B20_Temp (°C),DewPoint (°C),Status,Core1_Temp_C,Core1_Load_pct,Core2_Temp_C,Core2_Load_pct,Package_Temp_C,Package_Power_W,CPU_Total_Load_pct,volt
0,2025-09-22 14:22:50,21.8,57.0,19.94,12.98,SAFE,23.0,20.00,19.0,20.00,25.0,5.05,100.00,3
1,2025-09-22 14:15:12,21.0,62.0,19.00,13.51,SAFE,23.0,20.00,20.0,20.00,25.0,4.97,100.00,3
2,2025-09-22 14:18:56,21.5,59.0,18.94,13.22,SAFE,24.0,20.00,19.0,20.00,24.0,5.09,100.00,3
3,2025-09-22 14:21:26,21.4,59.0,19.87,13.13,SAFE,24.0,20.00,19.0,20.00,24.0,5.06,100.00,3
4,2025-09-22 14:21:28,21.4,59.0,19.87,13.13,SAFE,24.0,20.00,19.0,20.00,24.0,5.30,100.00,3
5,2025-09-22 15:10:51,23.4,63.0,20.94,16.03,SAFE,22.0,20.00,18.0,20.00,22.0,5.05,100.00,5
6,2025-09-22 15:11:01,23.4,63.0,21.00,16.03,SAFE,22.0,20.00,18.0,20.00,22.0,4.91,100.00,5
7,2025-09-22 15:10:28,23.4,62.0,20.87,15.78,SAFE,22.0,20.00,18.0,20.00,22.0,5.16,100.00,5
8,2025-09-22 15:10:49,23.4,63.0,21.00,16.03,SAFE,22.0,20.00,19.0,20.00,22.0,5.09,100.00,5
9,2025-09-22 15:10:30,23.4,62.0,20.94,15.78,SAFE,22.0,20.00,19.0,20.00,22.0,4.97,100.00,5
10,2025-09-22 15:26:11,23.4,63.0,21.44,16.03,SAFE,20.0,20.00,15.0,20.00,20.0,4.89,100.00,7
11,2025-09-22 15:26:15,23.4,63.0,21.44,16.03,SAFE,20.0,20.00,16.0,20.00,20.0,5.15,100.00,7
12,2025-09-22 15:26:27,23.4,63.0,21.44,16.03,SAFE,20.0,20.00,16.0,20.00,21.0,5.43,100.00,7
13,2025-09-22 15:26:32,23.4,63.0,21.37,16.03,SAFE,20.0,20.00,16.0,20.00,20.0,4.95,100.00,7
14,2025-09-22 15:26:20,23.4,64.0,21.44,16.27,SAFE,20.0,20.00,17.0,20.00,20.0,5.11,100.00,7
15,2025-09-22 16:11:15,24.8,44.0,20.37,11.84,SAFE,20.0,20.00,15.0,20.00,20.0,5.16,100.00,9
16,2025-09-22 16:18:06,24.8,44.0,20.19,11.84,SAFE,20.0,20.00,15.0,20.00,21.0,5.09,100.00,9
17,2025-09-22 16:21:43,24.8,43.0,20.12,11.49,SAFE,20.0,20.00,15.0,20.00,21.0,5.02,100.00,9
18,2025-09-22 16:11:52,24.8,44.0,20.37,11.84,SAFE,20.0,20.00,16.0,20.00,21.0,5.50,100.00,9
19,2025-09-22 16:13:22,25.3,44.0,20.37,12.29,SAFE,20.0,20.00,16.0,20.00,20.0,5.19,100.00,9
20,2025-09-22 16:28:26,23.8,44.0,19.94,10.93,SAFE,19.0,20.00,13.0,20.00,19.0,4.86,100.00,11
21,2025-09-22 16:28:34,23.8,44.0,19.94,10.93,SAFE,19.0,20.00,13.0,20.00,20.0,4.94,100.00,11
22,2025-09-22 16:28:36,23.8,44.0,19.94,10.93,SAFE,19.0,20.00,13.0,20.00,19.0,5.02,100.00,11
23,2025-09-22 16:28:38,23.8,44.0,19.87,10.93,SAFE,19.0,20.00,13.0,20.00,20.0,5.00,100.00,11
24,2025-09-22 16:28:50,23.8,44.0,19.94,10.93,SAFE,19.0,20.00,15.0,20.00,19.0,5.07,100.00,11
25,2025-09-23 09:42:32,16.7,60.0,16.12,8.95,SAFE,18.0,20.00,15.0,20.00,18.0,5.21,100.00,3
26,2025-09-23 09:42:41,16.6,60.0,16.12,8.86,SAFE,18.0,20.00,16.0,20.00,18.0,4.98,100.00,3
27,2025-09-23 09:43:03,17.0,61.0,16.12,9.48,SAFE,19.0,20.00,13.0,20.00,19.0,4.91,100.00,3
28,2025-09-23 09:42:30,17.0,60.0,16.12,9.23,SAFE,19.0,20.00,13.0,20.00,19.0,5.30,100.00,3
29,2025-09-23 09:43:55,17.0,63.0,16.31,9.96,SAFE,19.0,20.00,15.0,20.00,19.0,5.08,100.00,3
30,2025-09-23 10:23:06,19.4,65.0,18.44,12.71,SAFE,17.0,12.31,13.0,13.08,17.0,3.80,12.69,5
31,2025-09-23 10:13:27,19.8,69.0,18.69,14.00,SAFE,17.0,20.00,16.0,20.00,18.0,5.12,100.00,5
32,2025-09-23 10:13:13,19.8,69.0,18.69,14.00,SAFE,18.0,20.00,13.0,20.00,18.0,5.36,100.00,5
33,2025-09-23 10:13:24,19.8,69.0,18.69,14.00,SAFE,18.0,20.00,13.0,20.00,19.0,5.18,100.00,5
34,2025-09-23 10:13:26,19.8,69.0,18.69,14.00,SAFE,18.0,20.00,13.0,20.00,18.0,5.17,100.00,5